# Generated by Django 4.2.11 on 2024-04-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
