# Generated by Django 4.2.11 on 2024-04-22 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
