from django.shortcuts import render

# DJANGO USA ESTE ARCHIVO PARA SUS CONTROLLER SEGUN LA APP, DAJANGO ES MVT NO MVC, DONDE LAS VISTAS SON COMO LOS CONTROLLERS DE LOS MVC

# Create your views here.
